# C++ build
language: cpp
compiler:
    - gcc
    - clang
os:
- linux
#- osx

#before_install:
#  - sudo apt-get install cmake
before_script:  
    - mkdir -p build
    - cd build
    - cmake --version
    - cmake -DNOCOMPILERWARNINGS=1 ..

script:
  - make  
  - make package
  - ./oaunittest
  - ./pareto_example
  - ./oaranktest -I ../docs/examples/OAN56K28.oa
  - ./oainfo ../docs/examples/OAN56K28.oa

#addons:
#  artifacts: true
  
# Python build
#language: python
#python:
#  - "2.7"
#  - "3.4"
#
#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install swig
#install:
#  - python setup.py build

