# C++ build
language: cpp
compiler:
    - gcc
    - clang
os:
- linux
#- osx

#before_install:
#  - sudo apt-get install cmake
before_script:  
    - mkdir -p build
    - cd build
    - cmake --version
    - cmake -DNOCOMPILERWARNINGS=1 ..

script:
  - make  
  - make package
  - ./oaunittest
  - ./pareto_example
  - ./oaranktest -I ../docs/examples/OAN56K28.oa
  - ./oainfo ../docs/examples/OAN56K28.oa
  - ./oaextendsingle  -c ../oaconfig.txt -l 1
  - ./oasplit -i result-20.2-2-2.oa
  - ./oajoin split-split-0.oa split-split-1.oa -o temp.oa
  - ./oaextendsingle -m 3 -l 1 -c ../oaconfig3.txt --maxk 5 # J4 algorithm
  - ./oaconference -N 12 -k 6 -v 0


#addons:
#  artifacts: true
  
# Python build
#language: python
#python:
#  - "2.7"
#  - "3.4"
#
#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install swig
#install:
#  - python setup.py build

